{% set name = "fastapi-cli" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi_cli-{{ version }}.tar.gz
  sha256: 02b3b65956f526412515907a0793c9094abd4bfb5457b389f645b0ea6ba3605e

build:
  entry_points:
    - fastapi = fastapi_cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python
    - typer
    - uvicorn
    - rich-toolkit

test:
  imports:
    - fastapi_cli
  commands:
    - pip check
    - fastapi --help
  requires:
    - pip

about:
  home: https://github.com/tiangolo/fastapi-cli
  summary: Run and manage FastAPI apps from the command line with FastAPI CLI. 🚀
  license: MIT
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Dependency for chromadb
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - synapticarbors
